{
  "Grade1": [
    "Aalaa Mohmmed Abbas",
    "Ali Baqer Ali",
    "Ali Hassan Saeed",
    "Ali Hussain Ali",
    "Hoor Adel Ahmed",
    "Jood ammar ebrahim",
    "Khawla Adel Ahmed",
    "Masooma Mirza Mohammed",
    "Mohammed Ammar Merza",
    "Naser Dheya Mohamed",
    "Nasser Ebrahim Khalil",
    "Nebras Hussain Mohammed",
    "Noor alzahraa",
    "Sayed Karar Ebrahim",
    "Zainab Abdulla Hasan",
    "Zainab Aqeel Merza",
    "Zainab Sultan",
    "Zainab Zakareya A.Rasool"
  ],
  "Grade2": [
    "Abbas Hussain Abbas",
    "Ali Hussain Abbas",
    "Ali Mohamed Husain",
    "Basemah Mohamed Jaffar",
    "Fatima Mazen Habib",
    "Fatima S. Abdulla S. Mahdi",
    "Fatima S.Ali Hassan",
    "Hadi hameed abdulhadi",
    "Hussain zaki mohammed",
    "Jawad Hani Mahdi",
    "S. Ali S. Hasan Hashim",
    "Sara Jassim Mohammed",
    "Sayed Hadi Hussain Ali",
    "Sayed Hussain Hashim",
    "Zahraa Mahmood Majeed",
    "Zainab Husain Ahmed",
    "Zainab Hussain Mirza",
    "Zainab mohamed alnooh"
  ],
  "Grade3": [
    "Ahmed Hussain Mohmmed",
    "Ali Fathi Ahmed",
    "Batool S.Ali Hassan",
    "Haneen Ali Mohammed",
    "Hussain Ali Dawood",
    "Khawla S. Yasser Mahfoodh",
    "Mohamed sultan",
    "Noor Mohammed Ali",
    "Redha Fadhel Abbas",
    "Ruqaya Yusuf Amer Alhaddad",
    "Sayed Ali Talib Sayed Ali",
    "Sayed Hasan Ismail",
    "Wadeeah s.mahmood mahfoodh",
    "Yameen Yaqoob Yousif",
    "Yousif ahmed mohamed",
    "Zahra Mahmood Mohammed",
    "Zainab Ali Hussain",
    "Zainab Mohammed Salman"
  ],
  "Grade4": [
    "Ali Hussain A. Hassan",
    "Banana Zakareya A.Rasool",
    "Hadi Abaulfattah Abdulwahed",
    "Hasan Ahmed Abdulla",
    "Hussain abdulla mohamed",
    "Layal Jassim Mohammed",
    "Mohamed Ali yusuf",
    "Mohammed Adel Ahmed",
    "Mohammed Hussain Albasha",
    "Moosa jaffar mohammed",
    "Redha Mohammed Hassan",
    "Ruqaya Sayed Mohammed",
    "S. Ahmed Ali Mohammed",
    "Sara Sadeq Hasan",
    "Zahraa Hussain A. Nabi",
    "Zahraa Hussain Mirza"
  ],
  "Grade5": [
    "Abdulla Hussain Ali",
    "Ahmed Ali Abdulhasan",
    "Ali Hadi Farouq",
    "Ali Hussain Ahmed",
    "Husain Kumeel Taqi",
    "Hussain Ahmed Ali",
    "Kawthar S. Ahmed",
    "Mariam Aqeel",
    "Mariam yaseen alaswad",
    "Mohamed Dheya Mohamed",
    "Rabab Jaafar",
    "Redha Mahdi Moosa",
    "S. Mujtaba S. Abdulla S. Mahdi",
    "Sayed Hashim Ali Hussain",
    "Zahraa Ali Hussain",
    "Zainab Sayed Mohamed Alawi"
  ],
  "Grade6": [
    "Ahmed fadhel merza",
    "Baneen Abdulla Hasan",
    "Fatima A.Raof A.Rahem",
    "Fatima jaafar ahmed",
    "Fatima Sayed Ashraf",
    "Hasan Jasim Abbas",
    "Hawraa Abdulkarim Mohamed",
    "Hussain Fathi Ahmed",
    "Jawad Salah Ahmed",
    "Kawthar Hussain Mirza",
    "Mohmmed Hussain Mohmmed",
    "Mohmmed jaafar ahmed",
    "Nawraa zaki mohammed",
    "Sayed Mohammed Hussain Ali",
    "Yousif Yaqoob Yousif",
    "Zahraa Haider Mohsen"
  ],
  "Level1": [
    "Alaa Abdulla Hasan",
    "Ali Hassan Abdullah",
    "Ali Mohamed hasan",
    "Fatima Husain Ahmed",
    "Hadi mahdi moosa",
    "Hassan Hussain Mohammed",
    "Hawra Mahmood Mohammed",
    "Karrar Mahmood Mohammed",
    "Maryam Dheya Mohamed",
    "Mohamed amin Hasan",
    "Mohammed Ahmed Hussain",
    "Mohammed jassim saeed",
    "Safa ammar ebrahim",
    "Yaqeen Hassan Saeed"
  ],
  "Level2": [
    "Ali husain Ali albasha",
    "Alyaa Ahmed Hussain",
    "ammar hussain a.nabi",
    "Fatima Adnan Abbas",
    "Hasan Mohamed Ahmed",
    "Hassan Adel Ebrahim",
    "Hassan Jawad Juma",
    "Hussain Ali Saleh",
    "Ibrahim Abbas Mushaimea",
    "Mahdi Hani Mahdi",
    "Mahdi Saleh Ahmed",
    "Mohammed Abdulla Hassan",
    "Mohammed Hassan Ali",
    "Mohammed Jaafar Mohammad",
    "Naba Yusuf Amer",
    "Ruqaya Abdali Ramadhan",
    "Sajeda S.Mahmood S.Mahfoodh",
    "Zahraa jaafer Mohamed",
    "Zainab jaffer Mohamed"
  ],
  "Level3": [
    "Adam Fathi Ahmed",
    "Fatima Adnan Abbas Khalaf",
    "Fatima Ahmed A. Wahid",
    "Habib Mohammed Salman",
    "Hasan Mohammed Salman",
    "Karar Sadeq Hasan",
    "Mahdi Hani Mahdi",
    "Mahdi mohamed hasan",
    "Mohammed Ahmed A. Wahid",
    "Mohammed Aref Abdulmajeed",
    "Noor Hussain Ahmed",
    "Reem moosa aljamri",
    "Reem Sadeq Hasan",
    "Ruqaya Hani Mahdi",
    "S.Mohammed S.saleh Mahdi",
    "Sajeeda Sayed Salman Alawi",
    "Sayed Ameer Osama Alawi",
    "Zahraa S.Ali Hassan",
    "Zainab Abdali Ramadhan"
  ]
}
